<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WcfNetworkTester.Contracts\WcfNetworkTester.Contracts.csproj" />
  </ItemGroup>

</Project>
