<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" Version="2.4.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WcfNetworkTester.Contracts\WcfNetworkTester.Contracts.csproj" />
    <ProjectReference Include="..\WcfNetworkTester.Common\WcfNetworkTester.Common.csproj" />
  </ItemGroup>

</Project>
